### ISSUE TITLE
Process caused \"exec: \\\"/root/start.sh\\\": permission denied\"\n".

### ISSUE THREAD

**Issue by Wingman223** [ConSol/omd-labs-docker#11]
When trying to start the image via the command

sudo docker run -p 8443:443 consol/omd-labs-ubuntu

Tested on 2 different machines. One virual machine running Ubuntu 16.04 and one physical machine also running Ubuntu 16.04

The following error pops up

container_linux.go:247: starting container process caused "exec: \"/root/start.sh\": permission denied"
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/root/start.sh\\\": permission denied\"\n".

Full console log:

sudo docker run -p 8443:443 consol/omd-labs-ubuntu
Unable to find image 'consol/omd-labs-ubuntu:latest' locally
latest: Pulling from consol/omd-labs-ubuntu

660c48dd555d: Pull complete 
4c7380416e78: Pull complete 
421e436b5f80: Pull complete 
e4ce6c3651b3: Pull complete 
be588e74bd34: Pull complete 
c2b037e20e73: Pull complete 
764bf2ce64b7: Pull complete 
54f4d3152e06: Pull complete 
0b94f502c12f: Pull complete 
95a2ede5fb50: Pull complete 
3b474f12d095: Pull complete 
08b795a537ef: Pull complete 
2677429f8eae: Pull complete 
Digest: sha256:b4626c7ac6b5bcd55784aee809058f3dc0d1819f6154eb4f38e26c89e0de053c
Status: Downloaded newer image for consol/omd-labs-ubuntu:latest
container_linux.go:247: starting container process caused "exec: \"/root/start.sh\": permission denied"
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/root/start.sh\\\": permission denied\"\n".

**Comment by simonmeggle** [comment]
Thanks, solved by abcd9914e4ef1a73fa49152625e7bef8a0acc49a
Image build on Docker hub is triggered, please check again soon.

**Comment by Wingman223** [comment]
Still not working with the newest image on https://hub.docker.com/r/consol/omd-labs-ubuntu/. Same error appears even though the change "RUN chmod +x $HOME/start.sh" is included

**Comment by simonmeggle** [comment]
Ah, it seems you used the "latest" image. I just did the merge into this branch. The images are built now.

 
Side note: you wrote "with the newest image".... the newest build is tagged with "nightly". 
The latest tag means "latest stable" version, which is built from the 
 
"**master**" branch => omd-labs-ubuntu:**nightly** (daily build)
"**latest**" branch => omd-labs-ubuntu:**latest** (latest stable version)
